config/urls.py
from django.conf import settings
from django.conf.urls import include, url, handler400, handler403, handler404, handler500

from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.urls import path


handler404 = 'delay.core.views.error_404'
handler500 = 'delay.core.views.error_500'
handler403 = 'delay.core.views.error_403'
handler400 = 'delay.core.views.error_400'

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="index.html"), name="index"),
    url(r"^grappelli/", include('grappelli.urls')),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^users/", include("delay.users.urls", namespace="users")),
    url(r"^seller/", include("delay.seller.urls", namespace="seller")),
    url(r"^lots/", include("delay.lots.urls", namespace="lots")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

delay/lots/urls.py
from django.conf.urls import url
from django.urls import path

from delay.lots import views

app_name = "lots"

urlpatterns = [
    path("", views.AuctionRelevantListView.as_view(), name="relevant"),
    path("current/", views.AuctionCurrentListView.as_view(), name="current"),
    path("all/", views.AuctionAllListView.as_view(), name="all"),
    path("details/<int:id>/", views.detail_view, name="details"),
    path("details/<int:id>/charts/", views.charts_view, name="charts"),
    path("bidding/<int:id>/", views.bidding_view, name="bidding"),

    path("api/bids/<id>/", views.bids, name="bids"),
    path("api/bid/<id>/<int:value>/", views.bid, name="bid"),
    path("api/favorite/<id>/", views.favorite, name="favorite"),
    path("api/info/<id>/", views.get_online_data, name="online"),
    path("api/details/<id>/<type>/", views.get_auction_data, name="details"),
]

delay/seller/urls.py
from django.conf.urls import url

from delay.seller.views import (
    create_auction,
    api_create_auction,
    api_create_auction_2 
)

app_name = "seller"
urlpatterns = [
    url(r"^create-auction/$", create_auction, name="create"),
    url(r"^api/create-auction-2/$", api_create_auction_2, name="create_api_2"),
    url(r"^api/create-auction/$", api_create_auction, name="create_api"),
]

delay/users/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm

from .views import SignUpView, user_login_view, user_verify_view 

app_name = "users"

urlpatterns = [
    re_path(r"^signup/$", view=SignUpView.as_view(), name="signup"),
    re_path(r'^login/$', view=user_login_view, name='login'),
    re_path(r'^verify/$', view=user_verify_view, name='verify'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(
        r'^password_reset/$', 
        auth_views.PasswordResetView.as_view(
            form_class=PasswordResetForm,
            template_name='users/account/password_reset_form.html',
            email_template_name='users/account/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),

    re_path(
        r'^password_reset/done/$', 
        auth_views.PasswordResetDoneView.as_view(template_name="users/account/password_reset_done.html"), 
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url = reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm',
    ),

    re_path(
        r'^reset/done/$', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name='password_reset_complete'
    )

]

delay/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import AccountManager

class User(AbstractBaseUser, PermissionsMixin):

    # архив документов - набор отличается в зависимости от роли, в подсказке уточнить

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['email', 'last_name', 'first_name', 'company_name', 'company_type']

    COMPANY_TYPES = (
        ('B', 'Банк'),
        ('M', 'Микрофинансовая организация'),
        ('C', "Коллекторское агенство"),
    )

    email = models.EmailField("E-mail")
    phone = models.CharField("Телефон", max_length=20, unique=True)
    last_name = models.CharField("Фамилия", max_length=40)
    first_name = models.CharField("Имя", max_length=40)
    second_name = models.CharField("Отчество", max_length=30,  blank=True, default="")
    company_name = models.CharField("Название организации", max_length=40)
    company_type = models.CharField("Тип организации", choices=COMPANY_TYPES, max_length=1)
    company_logo = models.ImageField("Логотип", upload_to="users_logo/", null=True, blank=True)
    company_about = models.CharField("Краткое описание", max_length=1200, default="", blank=True)
    documents = models.FileField(upload_to="documents/")
    is_seller = models.BooleanField("Продавец", default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField("Активный аккаунт", default=False)
    last_login = models.DateTimeField(null=True, blank=True)

    objects = AccountManager()

    def __str__(self):
        return f'{self.first_name} / {self.phone}'

delay/core/views.py
from django.shortcuts import render


def error_400(request, exception):
    return render(request,'error_pages/400.html', status=400, context={})

def error_403(request, exception):
    return render(request,'error_pages/403.html', status=403, context={})

def error_404(request, exception, template_name='error_pages/404.html'):
    return render(request, template_name, locals())

def error_500(request):
    return render(request, 'error_pages/500.html', status=500, context={})

delay/lots/views.py
from django.db.utils import IntegrityError
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView
from django.conf import settings
from django.http import JsonResponse, HttpResponseNotFound, Http404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.shortcuts import render

from delay.helpers import ajax_required, serialize_excel
from delay.core.models import Auction, Bid
from delay.helpers import is_owner


class BaseAuctionListView(ListView):
    model = Auction
    context_object_name = "data"
    template_name = "auction/lots.html"

    def get_queryset(self, user, auctions, **kwargs):

        if user.is_staff:
            return auctions.order_by('status', '-timestamp_finish')

        if user.is_anonymous:
            return auctions.order_by('status', '-timestamp_finish')

        user_company_type = user.company_type
        user_own_auctions = auctions.filter(user=user)
            
        if user_company_type == 'B':
            qs = auctions.filter(accepted_banks=True)
        elif user_company_type == 'M':
            qs = auctions.filter(accepted_mfo=True)
        elif user_company_type == 'C':
            qs = auctions.filter(accepted_collection_agencies=True)

        return qs.union(user_own_auctions).order_by('status', '-timestamp_finish') # TODO продумать сортировку?


class AuctionAllListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_all()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "all"
        return context


class AuctionCurrentListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_started()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "current"
        return context


class AuctionRelevantListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        qs_1 = Auction.objects.get_approved()
        qs_2 = Auction.objects.get_started()
        auctions = qs_1.union(qs_2)
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "relevant"
        return context


@login_required
def detail_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(
        request, "auction/auction_details.html", context={'card': db_data}
    )


@login_required
def bidding_view(request, id):
    auction = Auction.objects.get(id=id)
    if auction.status != '2_S':
        return render(request, "error_pages/404.html")
    is_allowed = request.user.company_type in auction.allowed_company_types
    is_auction_owner = request.user == auction.user
    if is_auction_owner:
        role = 'author'
    elif is_allowed: # в продакшене фильтровать стаффов
        role = 'bidder'
    else:
        role = 'spectator'

    return render(
        request, "auction/auction_bidding.html", context={'card': auction, 'room_name': id, 'role': role}
    )


@ajax_required
@require_http_methods(["GET"])
def bids(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    response = {}
    for ix, bid in enumerate(bids):
        response[ix] = [bid.user.phone, bid.price, bid.step, bid.time]
    return JsonResponse(response)


@ajax_required
@require_http_methods(["GET"])
def get_online_data(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    bids_count = bids.count()

    if auction.closed_auction:
        if not bids_count:
            last_user_bid = auction.start_price
        else:
            last_user_bid = bids.filter(user=request.user).latest('time').price
        return JsonResponse({'count': bids_count, 'lastUserBid': last_user_bid})
    else:
        if not bids_count:
            return JsonResponse('No Bids', safe=False)
        bids_last = bids.first().price
        return JsonResponse({'count': bids_count, 'last': bids_last})


def charts_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(request, "auction/auction_analysis.html", context={'card': db_data})


@login_required
@ajax_required
@require_http_methods(["GET"])
def favorite(request, id):
    auction = Auction.objects.get(id=id)
    user = request.user
    if user in auction.bookmarks.all():
        auction.bookmarks.remove(user)
    else:
        auction.bookmarks.add(user)
    return JsonResponse({"count": auction.bookmarks.count()}, status=200) # TODO шедулинг на смс


@login_required
@ajax_required
@require_http_methods(["GET"])
def bid(request, id, value):
    print(request, id, value)
    auction = Auction.objects.get(id=id)
    new_bid = Bid(user=request.user, price=value, step=value)
    try:
        new_bid.save()
        auction.bids.add(new_bid)
        auction.save()
        return JsonResponse({'code': 'success', 'message': 'Ставка принята'})
    except Exception:
        transaction.rollback()
        return JsonResponse({'code': 'error', 'message': 'Не удалось принять ставку' })



@login_required
@ajax_required
@require_http_methods(["GET"])
def get_auction_data(request, id, type):
    data = Auction.objects.get(id=id)
    document = settings.MEDIA_ROOT + '/' + data.doc_register.name
    data_dict = serialize_excel(document)
    if type == 'chart-details':
        osz_list = sorted([row['osz'] for row in data_dict])
        chart_data = [[ix, val] for ix, val in enumerate(osz_list)]
        return JsonResponse(chart_data, safe=False)
    elif type == 'chart-analysis':
        return JsonResponse({
            'sex': sorted([row['sex'] for row in data_dict]), 
            'age': sorted([row['age'] for row in data_dict]),
            'region': sorted([row['region'] for row in data_dict]),
            'osz': sorted([row['osz'] for row in data_dict]),
            'delay': sorted([row['delayPeriod'] for row in data_dict]),
            }, safe=False)
    elif type == 'datatable':
        return JsonResponse(data_dict, safe=False)

delay/seller/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.files import File


from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import FileUploadParser, MultiPartParser, FormParser


from delay.helpers import AuthorRequiredMixin, _process_excel
from delay.core.models import Auction, AuctionQuerySet

from .serializers import AuctionSerializer

from config.settings.base import MEDIA_URL


@ensure_csrf_cookie
def create_auction(request, *args, **kwargs):
    form = AuctionDocumentForm()
    return render(request, "auction/auction_create.html", {"form": form})


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser, FileUploadParser])
def api_create_auction(request, *args, **kwargs):
    file_obj = request.data['file']
    
    osz, od, region, average_debt, average_delay, n_cases, multiregion = _process_excel(file_obj)
    data = {'osz': osz, 'od': od, 'region': region, 'average_debt': average_debt, 'average_delay': average_delay, 'n_cases': n_cases, 'multiregion': multiregion}
    return Response(json.dumps(data))


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def api_create_auction_2(request, *args, **kwargs):
    serializer = AuctionSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response('OK', 200)

delay/users/views.py
import json

from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from delay.helpers import ajax_required, generate_code, send_sms

from .models import User
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    template_name = 'users/account/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')


def user_login_view(request):
    if request.method == 'GET':
        return render(request, "users/account/login.html", context={'error': None})
    phone = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = User.objects.get(phone=phone)
    except Exception:
        return render(request, "users/account/login.html", context={'error': 'Аккаунт не найден'})
    if not check_password(password, user.password):
        return render(request, "users/account/login.html", context={'error': 'Неверный пароль'})
    request.session['phone'] = phone
    request.session['password'] = password
    return redirect('users:verify')


def user_verify_view(request):
    if request.method == 'GET':
        code = '22222' # generate_code()
        phone = request.session['phone']
        cache.set(f'{phone}_otp', code, 120)
        # send_sms(code, '+79969752375') # phone
        print(phone, cache.get(f'{phone}_otp'))
        return render(request, "users/account/verify.html")
    code = request.POST.get('code')
    print(code)
    phone = request.session['phone']
    correct_code = cache.get(f'{phone}_otp')
    if not correct_code:
        return render(request, "users/account/verify.html", context={'error': "Срок действия кода вышел. Мы отправили Вам новый"})
    if correct_code != code:
        return render(request, "users/account/verify.html", context={'error': "Неверный код. Мы отправили Вам новый"})
    user = authenticate(request, username=phone, password=request.session['password'])
    if not user:
        return render(request, "users/account/login.html", context={'error': 'Возникли проблемы при входе в аккаунт. Попробуйте еще раз'})
    login(request, user)
    print(user)
    return redirect('lots:all')

delay/templates/users/account/__ПРОВЕРИТЬ_account_password_reset_from_key_done.html
{% extends "account/base.html" %}

{% block head_title %}Смена пароля{% endblock %}

{% block inner %}
    <h1>Смена пароля</h1>
    <p>Ваш пароль был успешно изменен</p>
{% endblock %}

delay/templates/users/account/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Аутентификация{% endblock title %}

{% block head %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock head %}

{% block content %}
<div class="limiter">
  {% if error %}
  <div class="alert">
    <div class="alert__content" role="alert">
        <span class="alert__icon">
            <svg class="alert__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="#333333">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
            </svg>
        </span>
        <span class="alert__text">{{ error }}</span>
    </div>
  </div>
  {% endif %}
  <div class="login">
    <div class="login__title">Личный кабинет</div>
    <form class="login__form" method="post" x-data="form()" x-init="init()" @focusout="change" @input="change" @submit="submit($event)" novalidate>
      {% csrf_token %}
      <div class="login__formfield" x-bind:class="{'login__formfield-invalid':username.errorMessage}">
        <label class="login__formfield__label" for="phone">Телефон *</label>
        <input name="username" id="phone" class="login__formfield__input login__phone__input" type="text" autocomplete="off" title="" data-rules='["required", "phone"]' data-server-errors='[]' />
      </div> 
      <div class="login__formfield" x-bind:class="{'login__formfield-invalid':password.errorMessage}">
        <label class="login__formfield__label" for="password">Пароль *</label>
        <input name="password" id="password" class="login__formfield__input login__password__input" type="password" autocomplete="off" title="" data-rules='["required", "minimum:6"]' data-server-errors='[]' /> 
      </div> 
      <button class="login__button" type="submit"> Войти &raquo; </button> 
    </form>
    <div class="login__links">
      <a class="login__link" href="{% url 'users:signup' %}">Регистрация</a>
      <a class="login__link" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    </div>
  </div>

  <div hidden class="spinner" id="spinner"></div>
  <div hidden class="overlay" id="overlay"></div>

</div>
{% endblock content %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/gh/mattkingshott/iodine@3/dist/iodine.min.js"></script>
<script src="{% static 'js/login.js' %}"></script>
{% endblock javascript %}

delay/templates/users/account/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block title %} Сброс пароля {% endblock title %}
{% block head %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock head %}

{% block content %}
<div class="limiter">
<div class="reset__done" id="reset-wrapper">
    <div class="reset__done__header">Сброс пароля</div>
    <div class="reset__done__main">
        <div class="reset__done__alert">
            <span class="reset__done__alert__span">
                <svg fill="currentColor" viewBox="0 0 20 20" class="reset__done__svg">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
                </svg>
            </span>
        </div>
        <div class="reset__done__content">Вам отправлено письмо</div>
        <div class="reset__done__description">Для восстановления пароля необходимо перейти по ссылке из письма</div>
    </div>
    <p class="reset__done__footer">При возникновении проблем, пожалуйста, свяжитесь с нами</p>
</div>
</div>
{% endblock content %}

delay/templates/users/account/password_reset_email.html
{% autoescape off %}

Мы получили Ваш запрос на сброс пароля.

Пожалуйста, перейдите по следующей ссылке и задайте новый пароль для вашего аккаунта.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Спасибо, что выбрали Delay

{% endautoescape %}

delay/templates/users/account/password_reset_form.html
{% extends "base.html" %}
{% load static %}

{% block title %} Сброс пароля {% endblock title %}
{% block head %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock head %}

{% block content %}
<div class="limiter">
    <div class="reset">
        <div class="reset__title">Сброс пароля</div>
        <form  class="reset__form" method="post">
            {% csrf_token %}
            <div class="reset__formfield">
                <label for="email" class="reset__label">E-mail *</label>
                <input id="email" name="email" autocomplete="off" tabindex="0" type="email" class="reset__input">
            </div>
            <input class="reset__button" type="submit" name="Отправить" value="Отправить" id="submit-id-">
        </form>
        <p class="reset__footer">При возникновении проблем, пожалуйста, свяжитесь с нами</p>
    </div>
</div>
{% endblock content %}

delay/templates/users/account/verify.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Аутентификация{% endblock title %}

{% block head %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock head %}

{% block content %}
<div class="limiter">
    {% if error %}
    <div class="alert">
      <div class="alert__content" role="alert">
          <span class="alert__icon">
              <svg class="alert__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="#333333">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
              </svg>
          </span>
          <span class="alert__text">{{ error }}</span>
      </div>
    </div>
    {% endif %}
  <div class="modal modal-active">
    <div class="modal__content">
      <p class="modal__heading">Верификация</p>
      <p class="modal__text">Вам отправлено СМС-сообщение. Введите код</p>
      <div class="modal__input">
        <input type="tel" maxlength="1" pattern="[0-9]" class="modal__code">
        <input type="tel" maxlength="1" pattern="[0-9]" class="modal__code">
        <input type="tel" maxlength="1" pattern="[0-9]" class="modal__code">
        <input type="tel" maxlength="1" pattern="[0-9]" class="modal__code">
        <input type="tel" maxlength="1" pattern="[0-9]" class="modal__code">
      </div>
      <form method="POST" class="modal__form">
          {% csrf_token %}
          <input class="modal__code__accumulator" name="code" type="text" hidden>
          <div class="modal__button_group">
            <button class="modal__button_confirm" type="submit" disabled>Войти</button>
            <a class="modal__button_retry" href="{% url 'users:login' %}">Назад</a>
          </div>
      </form>
    </div>
  </div>

  <div class="login">
    <div class="login__title">Личный кабинет</div>
    <div class="login__form">
      <div class="login__phone">
        <svg class="login__svg" fill="none" stroke="#444444" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z"></path>
        </svg>
        <input name="username" class="login__phone__input" type="text" placeholder="Телефон" autocomplete="off" required />
      </div>
      <div class="login__password">
        <svg class="login__svg" fill="none" stroke="#444444" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"></path>
        </svg>
        <input name="password" class="login__password__input" type="password" minlength="6" maxlength="40" placeholder="Пароль" autocomplete="off" required /> 
      </div>
      <button class="login__submit"> Войти &raquo; </button> 
    </div>
    <input type="button" class="login__button" value="Получить код &raquo;" />
    <div class="login__links">
      <a class="login__link" href="{% url 'users:signup' %}">Регистрация</a>
      <a class="login__link" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    </div>
  </div>

  <div hidden class="spinner" id="spinner"></div>
  <div class="overlay" id="overlay"></div>

</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/verify.js' %}"></script>
{% endblock javascript %}