config/urls.py
from django.conf import settings
from django.conf.urls import include, url, handler400, handler403, handler404, handler500

from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.urls import path


handler404 = 'delay.core.views.error_404'
handler500 = 'delay.core.views.error_500'
handler403 = 'delay.core.views.error_403'
handler400 = 'delay.core.views.error_400'

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="index.html"), name="index"),
    url(r"^grappelli/", include('grappelli.urls')),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^users/", include("delay.users.urls", namespace="users")),
    url(r"^seller/", include("delay.seller.urls", namespace="seller")),
    url(r"^lots/", include("delay.lots.urls", namespace="lots")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

delay/lots/urls.py
from django.conf.urls import url
from django.urls import path

from delay.lots import views

app_name = "lots"

urlpatterns = [
    path("", views.AuctionRelevantListView.as_view(), name="relevant"),
    path("current/", views.AuctionCurrentListView.as_view(), name="current"),
    path("all/", views.AuctionAllListView.as_view(), name="all"),
    path("details/<int:id>/", views.detail_view, name="details"),
    path("details/<int:id>/charts/", views.charts_view, name="charts"),
    path("bidding/<int:id>/", views.bidding_view, name="bidding"),

    path("api/bids/<id>/", views.bids, name="bids"),
    path("api/bid/<id>/<int:value>/", views.bid, name="bid"),
    path("api/favorite/<id>/", views.favorite, name="favorite"),
    path("api/info/<id>/", views.get_online_data, name="online"),
    path("api/details/<id>/<type>/", views.get_auction_data, name="details"),
]

delay/seller/urls.py
from django.conf.urls import url

from delay.seller.views import (
    create_auction,
    api_create_auction,
    api_create_auction_2 
)

app_name = "seller"
urlpatterns = [
    url(r"^create-auction/$", create_auction, name="create"),
    url(r"^api/create-auction-2/$", api_create_auction_2, name="create_api_2"),
    url(r"^api/create-auction/$", api_create_auction, name="create_api"),
]

delay/users/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm

from .views import SignUpView, user_login_view, user_verify_view 

app_name = "users"

urlpatterns = [
    re_path(r"^signup/$", view=SignUpView.as_view(), name="signup"),
    re_path(r'^login/$', view=user_login_view, name='login'),
    re_path(r'^verify/$', view=user_verify_view, name='verify'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(
        r'^password_reset/$', 
        auth_views.PasswordResetView.as_view(
            form_class=PasswordResetForm,
            template_name='users/account/password_reset_form.html',
            email_template_name='users/account/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),

    re_path(
        r'^password_reset/done/$', 
        auth_views.PasswordResetDoneView.as_view(template_name="users/account/password_reset_done.html"), 
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url = reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm',
    ),

    re_path(
        r'^reset/done/$', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name='password_reset_complete'
    )

]

delay/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation

from delay.users.models import User


class CustomUserCreationForm(UserCreationForm):

    error_message = UserCreationForm.error_messages.update(
        {"duplicate_phone": "Данный телефонный номер уже используется в системе"}
    )

    password2 = None

    class Meta:
        model = User
        fields = ['email', 'phone', 'password1', 'last_name', 'first_name', 'company_name', 'company_type', 'documents']

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        try:
            password_validation.validate_password(password1, self.instance)
        except forms.ValidationError as error:
            self.add_error('password1', error)
        return password1

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        try:
            User.objects.get(phone=phone)
        except User.DoesNotExist:
            return phone.replace('(', '').replace(')', '').replace('-', '')
        raise forms.ValidationError(self.error_messages["duplicate_phone"])

delay/core/views.py
from django.shortcuts import render


def error_400(request, exception):
    return render(request,'error_pages/400.html', status=400, context={})

def error_403(request, exception):
    return render(request,'error_pages/403.html', status=403, context={})

def error_404(request, exception, template_name='error_pages/404.html'):
    return render(request, template_name, locals())

def error_500(request):
    return render(request, 'error_pages/500.html', status=500, context={})

delay/lots/views.py
from django.db.utils import IntegrityError
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView
from django.conf import settings
from django.http import JsonResponse, HttpResponseNotFound, Http404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.shortcuts import render

from delay.helpers import ajax_required, serialize_excel
from delay.core.models import Auction, Bid
from delay.helpers import is_owner


class BaseAuctionListView(ListView):
    model = Auction
    context_object_name = "data"
    template_name = "auction/lots.html"

    def get_queryset(self, user, auctions, **kwargs):

        if user.is_staff:
            return auctions.order_by('status', '-timestamp_finish')

        if user.is_anonymous:
            return auctions.order_by('status', '-timestamp_finish')

        user_company_type = user.company_type
        user_own_auctions = auctions.filter(user=user)
            
        if user_company_type == 'B':
            qs = auctions.filter(accepted_banks=True)
        elif user_company_type == 'M':
            qs = auctions.filter(accepted_mfo=True)
        elif user_company_type == 'C':
            qs = auctions.filter(accepted_collection_agencies=True)

        return qs.union(user_own_auctions).order_by('status', '-timestamp_finish') # TODO продумать сортировку?


class AuctionAllListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_all()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "all"
        return context


class AuctionCurrentListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_started()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "current"
        return context


class AuctionRelevantListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        qs_1 = Auction.objects.get_approved()
        qs_2 = Auction.objects.get_started()
        auctions = qs_1.union(qs_2)
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "relevant"
        return context


@login_required
def detail_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(
        request, "auction/auction_details.html", context={'card': db_data}
    )


@login_required
def bidding_view(request, id):
    auction = Auction.objects.get(id=id)
    if auction.status != '2_S':
        return render(request, "error_pages/404.html")
    is_allowed = request.user.company_type in auction.allowed_company_types
    is_auction_owner = request.user == auction.user
    if is_auction_owner:
        role = 'author'
    elif is_allowed: # в продакшене фильтровать стаффов
        role = 'bidder'
    else:
        role = 'spectator'

    return render(
        request, "auction/auction_bidding.html", context={'card': auction, 'room_name': id, 'role': role}
    )


@ajax_required
@require_http_methods(["GET"])
def bids(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    response = {}
    for ix, bid in enumerate(bids):
        response[ix] = [bid.user.phone, bid.price, bid.step, bid.time]
    return JsonResponse(response)


@ajax_required
@require_http_methods(["GET"])
def get_online_data(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    bids_count = bids.count()

    if auction.closed_auction:
        if not bids_count:
            last_user_bid = auction.start_price
        else:
            last_user_bid = bids.filter(user=request.user).latest('time').price
        return JsonResponse({'count': bids_count, 'lastUserBid': last_user_bid})
    else:
        if not bids_count:
            return JsonResponse('No Bids', safe=False)
        bids_last = bids.first().price
        return JsonResponse({'count': bids_count, 'last': bids_last})


def charts_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(request, "auction/auction_analysis.html", context={'card': db_data})


@login_required
@ajax_required
@require_http_methods(["GET"])
def favorite(request, id):
    auction = Auction.objects.get(id=id)
    user = request.user
    if user in auction.bookmarks.all():
        auction.bookmarks.remove(user)
    else:
        auction.bookmarks.add(user)
    return JsonResponse({"count": auction.bookmarks.count()}, status=200) # TODO шедулинг на смс


@login_required
@ajax_required
@require_http_methods(["GET"])
def bid(request, id, value):
    print(request, id, value)
    auction = Auction.objects.get(id=id)
    new_bid = Bid(user=request.user, price=value, step=value)
    try:
        new_bid.save()
        auction.bids.add(new_bid)
        auction.save()
        return JsonResponse({'code': 'success', 'message': 'Ставка принята'})
    except Exception:
        transaction.rollback()
        return JsonResponse({'code': 'error', 'message': 'Не удалось принять ставку' })



@login_required
@ajax_required
@require_http_methods(["GET"])
def get_auction_data(request, id, type):
    data = Auction.objects.get(id=id)
    document = settings.MEDIA_ROOT + '/' + data.doc_register.name
    data_dict = serialize_excel(document)
    if type == 'chart-details':
        osz_list = sorted([row['osz'] for row in data_dict])
        chart_data = [[ix, val] for ix, val in enumerate(osz_list)]
        return JsonResponse(chart_data, safe=False)
    elif type == 'chart-analysis':
        return JsonResponse({
            'sex': sorted([row['sex'] for row in data_dict]), 
            'age': sorted([row['age'] for row in data_dict]),
            'region': sorted([row['region'] for row in data_dict]),
            'osz': sorted([row['osz'] for row in data_dict]),
            'delay': sorted([row['delayPeriod'] for row in data_dict]),
            }, safe=False)
    elif type == 'datatable':
        return JsonResponse(data_dict, safe=False)

delay/seller/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.files import File


from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import FileUploadParser, MultiPartParser, FormParser


from delay.helpers import AuthorRequiredMixin, _process_excel
from delay.core.models import Auction, AuctionQuerySet

from .serializers import AuctionSerializer

from config.settings.base import MEDIA_URL


@ensure_csrf_cookie
def create_auction(request, *args, **kwargs):
    form = AuctionDocumentForm()
    return render(request, "auction/auction_create.html", {"form": form})


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser, FileUploadParser])
def api_create_auction(request, *args, **kwargs):
    file_obj = request.data['file']
    
    osz, od, region, average_debt, average_delay, n_cases, multiregion = _process_excel(file_obj)
    data = {'osz': osz, 'od': od, 'region': region, 'average_debt': average_debt, 'average_delay': average_delay, 'n_cases': n_cases, 'multiregion': multiregion}
    return Response(json.dumps(data))


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def api_create_auction_2(request, *args, **kwargs):
    serializer = AuctionSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response('OK', 200)

delay/users/views.py
import json

from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from delay.helpers import ajax_required, generate_code, send_sms

from .models import User
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    template_name = 'users/account/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')


def user_login_view(request):
    if request.method == 'GET':
        return render(request, "users/account/login.html", context={'error': None})
    phone = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = User.objects.get(phone=phone)
    except Exception:
        return render(request, "users/account/login.html", context={'error': 'Аккаунт не найден'})
    if not check_password(password, user.password):
        return render(request, "users/account/login.html", context={'error': 'Неверный пароль'})
    request.session['phone'] = phone
    request.session['password'] = password
    return redirect('users:verify')


def user_verify_view(request):
    if request.method == 'GET':
        code = '22222' # generate_code()
        phone = request.session['phone']
        cache.set(f'{phone}_otp', code, 120)
        # send_sms(code, '+79969752375') # phone
        print(phone, cache.get(f'{phone}_otp'))
        return render(request, "users/account/verify.html")
    code = request.POST.get('code')
    print(code)
    phone = request.session['phone']
    correct_code = cache.get(f'{phone}_otp')
    if not correct_code:
        return render(request, "users/account/verify.html", context={'error': "Срок действия кода вышел. Мы отправили Вам новый"})
    if correct_code != code:
        return render(request, "users/account/verify.html", context={'error': "Неверный код. Мы отправили Вам новый"})
    user = authenticate(request, username=phone, password=request.session['password'])
    if not user:
        return render(request, "users/account/login.html", context={'error': 'Возникли проблемы при входе в аккаунт. Попробуйте еще раз'})
    login(request, user)
    print(user)
    return redirect('lots:all')

delay/templates/_base_components/_card_icons.html
<div class="card__icons">
    <div class="card__icons__top">
        {% if card.closed_auction is False %}
        <div aria-label="Открытый аукцион" data-balloon-pos="up">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#f3f3f0" width="24" height="24"><path d="M15.5 12a3.5 3.5 0 11-7 0 3.5 3.5 0 017 0z"></path><path fill-rule="evenodd" d="M12 3.5c-3.432 0-6.125 1.534-8.054 3.24C2.02 8.445.814 10.352.33 11.202a1.6 1.6 0 000 1.598c.484.85 1.69 2.758 3.616 4.46C5.876 18.966 8.568 20.5 12 20.5c3.432 0 6.125-1.534 8.054-3.24 1.926-1.704 3.132-3.611 3.616-4.461a1.6 1.6 0 000-1.598c-.484-.85-1.69-2.757-3.616-4.46C18.124 5.034 15.432 3.5 12 3.5zM1.633 11.945c.441-.774 1.551-2.528 3.307-4.08C6.69 6.314 9.045 5 12 5c2.955 0 5.309 1.315 7.06 2.864 1.756 1.553 2.866 3.307 3.307 4.08a.111.111 0 01.017.056.111.111 0 01-.017.056c-.441.774-1.551 2.527-3.307 4.08C17.31 17.685 14.955 19 12 19c-2.955 0-5.309-1.315-7.06-2.864-1.756-1.553-2.866-3.306-3.307-4.08A.11.11 0 011.616 12a.11.11 0 01.017-.055z"></path></svg>
        </div>
        {% endif %}
        <div aria-label="Документы проверены" data-balloon-pos="up">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#f3f3f0" width="24" height="24"><path d="M3.5 3.75a.25.25 0 01.25-.25h13.5a.25.25 0 01.25.25v10a.75.75 0 001.5 0v-10A1.75 1.75 0 0017.25 2H3.75A1.75 1.75 0 002 3.75v16.5c0 .966.784 1.75 1.75 1.75h7a.75.75 0 000-1.5h-7a.25.25 0 01-.25-.25V3.75z"></path><path d="M6.25 7a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5zm-.75 4.75a.75.75 0 01.75-.75h4.5a.75.75 0 010 1.5h-4.5a.75.75 0 01-.75-.75zm16.28 4.53a.75.75 0 10-1.06-1.06l-4.97 4.97-1.97-1.97a.75.75 0 10-1.06 1.06l2.5 2.5a.75.75 0 001.06 0l5.5-5.5z"></path></svg>
        </div>
        <div aria-label="Надежный продавец" data-balloon-pos="up">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#f3f3f0" width="24" height="24"><path d="M16.53 9.78a.75.75 0 00-1.06-1.06L11 13.19l-1.97-1.97a.75.75 0 00-1.06 1.06l2.5 2.5a.75.75 0 001.06 0l5-5z"></path><path fill-rule="evenodd" d="M12.54.637a1.75 1.75 0 00-1.08 0L3.21 3.312A1.75 1.75 0 002 4.976V10c0 6.19 3.77 10.705 9.401 12.83.386.145.812.145 1.198 0C18.229 20.704 22 16.19 22 10V4.976c0-.759-.49-1.43-1.21-1.664L12.54.637zm-.617 1.426a.25.25 0 01.154 0l8.25 2.676a.25.25 0 01.173.237V10c0 5.461-3.28 9.483-8.43 11.426a.2.2 0 01-.14 0C6.78 19.483 3.5 15.46 3.5 10V4.976c0-.108.069-.203.173-.237l8.25-2.676z"></path></svg>  
        </div>
    </div>
    {% if card.status == '1_A' %}
    <div class="card__icons__middle favorite" aria-label="В избранное" data-balloon-pos="up">
        {% if user in card.bookmarks.all %}
        <svg class="clicked" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#f3f3f0" width="64" height="64">
        {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#f3f3f0" width="64" height="64">
        {% endif %}
            <path fill-rule="evenodd" d="M12 .25a.75.75 0 01.673.418l3.058 6.197 6.839.994a.75.75 0 01.415 1.279l-4.948 4.823 1.168 6.811a.75.75 0 01-1.088.791L12 18.347l-6.117 3.216a.75.75 0 01-1.088-.79l1.168-6.812-4.948-4.823a.75.75 0 01.416-1.28l6.838-.993L11.328.668A.75.75 0 0112 .25zm0 2.445L9.44 7.882a.75.75 0 01-.565.41l-5.725.832 4.143 4.038a.75.75 0 01.215.664l-.978 5.702 5.121-2.692a.75.75 0 01.698 0l5.12 2.692-.977-5.702a.75.75 0 01.215-.664l4.143-4.038-5.725-.831a.75.75 0 01-.565-.41L12 2.694z"></path>
            <text x="50%" y="52%" dominant-baseline="middle" text-anchor="middle" font-size="7px">{{ card.bookmarks.count }}</text>
        </svg>
    </div>
    {% elif card.status == '2_S' and card.closed_auction == False %}
    <div class="card__icons__middle" id="bid" aria-label="Сделать ставку" data-balloon-pos="up">
        <a href="{% url 'lots:bidding' card.id %}">
            <svg height="64" width="64" viewBox="0 0 450 480" xmlns="http://www.w3.org/2000/svg">
                <path d="m255 300v197c0 8.402344-6.597656 15-15 15h-30c-8.402344 0-15-6.597656-15-15v-197zm0 0" fill="#a8d3d8"/>
                <path d="m255 300v197c0 8.402344-6.597656 15-15 15h-15v-212zm0 0" fill="#7ca1b1"/>
                <path d="m450 15v270c0 8.402344-6.597656 15-15 15h-420c-8.402344 0-15-6.597656-15-15v-270c0-8.402344 6.597656-15 15-15h420c8.402344 0 15 6.597656 15 15zm0 0" fill="crimson"/>
                <path d="m450 15v270c0 8.402344-6.597656 15-15 15h-210v-300h210c8.402344 0 15 6.597656 15 15zm0 0" fill="crimson"/>
                <path d="m240 75v120c0 8.402344-6.597656 15-15 15s-15-6.597656-15-15v-120c0-8.402344 6.597656-15 15-15s15 6.597656 15 15zm0 0" fill="#deecf1"/>
                <path d="m180 105c0-24.8125-20.1875-45-45-45h-30c-8.289062 0-15 6.710938-15 15v120c0 8.289062 6.710938 15 15 15h30c24.8125 0 45-20.1875 45-45 0-11.566406-4.507812-22.019531-11.703125-30 7.195313-7.980469 11.703125-18.433594 11.703125-30zm-60-15h15c8.277344 0 15 6.722656 15 15s-6.722656 15-15 15h-15zm15 90h-15v-30h15c8.277344 0 15 6.722656 15 15s-6.722656 15-15 15zm0 0" fill="#deecf1"/>
                <path d="m315 210h-30c-8.289062 0-15-6.710938-15-15v-120c0-8.289062 6.710938-15 15-15h30c24.8125 0 45 20.1875 45 45v60c0 24.8125-20.1875 45-45 45zm-15-30h15c8.277344 0 15-6.722656 15-15v-60c0-8.277344-6.722656-15-15-15h-15zm0 0" fill="#a8d3d8"/>
                <path d="m225 210v-150c8.402344 0 15 6.597656 15 15v120c0 8.402344-6.597656 15-15 15zm0 0" fill="#a8d3d8"/>
                <path d="m315 270h-180c-8.402344 0-15 6.597656-15 15v30c0 8.402344 6.597656 15 15 15h180c8.402344 0 15-6.597656 15-15v-30c0-8.402344-6.597656-15-15-15zm0 0" fill="#deecf1"/>
                <path d="m330 285v30c0 8.402344-6.597656 15-15 15h-90v-60h90c8.402344 0 15 6.597656 15 15zm0 0" fill="#a8d3d8"/>
            </svg>
        </a>
    </div>
    {% elif card.status == '2_S' and card.closed_auction == True %}
    <div class="card__icons__middle" id="bid" aria-label="Аукцион закрытых предложений" data-balloon-pos="top">
        <span style="margin-top: 0.25rem;">
            <svg height="48" width="48" fill="none" stroke="white" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
            </svg>
        </span>  
    </div>
    <p class="card__online__data card__online__count">
        Ставок: <strong>{{ card.count_bids }}</strong>
    </p>      
    {% endif %}
    <div class="card__icons__bottom">
      <a href="{% url 'lots:details' card.id %}">Подробнее</a>
    </div>
</div>

delay/templates/_base_components/_user_navbar.html
{% load static %}

<nav class="navbar">
  <div class="navbar__left">
    <div class="navbar__logo">
      <img class="navbar__logo__image" src="{% static 'img/logo-white.svg' %}" alt="delay logo">
      <img class="navbar__logo__image-small" src="{% static 'img/favicon.png' %}" alt="delay logo">
    </div>
    <div class="navbar__links">
      <a href="{% url 'lots:relevant' %}" class="navbar__link navbar__link-active">Торги</a>
      <a href="#" class="navbar__link">Поддержка</a>
    </div>
  </div>

  <div class="navbar__right">
    {% if user.is_authenticated %}
    <button class="navbar__notify">
      <svg class="navbar__notify__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
      </svg>
    </button>

    <div x-data="{ open: false }" class="navbar__user">
      <button class="navbar__user__button" @click.prevent="open = !open" id="user-menu" aria-haspopup="true">
          <span class="navbar__user__name">{{ request.user.first_name }}</span>
          <svg class="navbar__user__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
      </button>
      <div class="navbar__user__dropdown" x-show="open" @click.away="open = false" :class="{ 'hidden': open === false }" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
        <a href="{% url 'users:logout' %}" class="navbar__user__item" role="menuitem">Выйти</a>
      </div>
    </div>
    {% else %}
    <a href="lots:login" class="navbar__link">Вход</a>
    <a href="lots:signup" class="navbar__link">Регистрация</a>
    {% endif %}
  </div>
</nav>

{% block javascript %}{% endblock %}