config/urls.py
from django.conf import settings
from django.conf.urls import include, url, handler400, handler403, handler404, handler500

from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.urls import path


handler404 = 'delay.core.views.error_404'
handler500 = 'delay.core.views.error_500'
handler403 = 'delay.core.views.error_403'
handler400 = 'delay.core.views.error_400'

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="index.html"), name="index"),
    url(r"^grappelli/", include('grappelli.urls')),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^users/", include("delay.users.urls", namespace="users")),
    url(r"^seller/", include("delay.seller.urls", namespace="seller")),
    url(r"^lots/", include("delay.lots.urls", namespace="lots")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

delay/lots/urls.py
from django.conf.urls import url
from django.urls import path

from delay.lots import views

app_name = "lots"

urlpatterns = [
    path("", views.AuctionRelevantListView.as_view(), name="relevant"),
    path("current/", views.AuctionCurrentListView.as_view(), name="current"),
    path("all/", views.AuctionAllListView.as_view(), name="all"),
    path("details/<int:id>/", views.detail_view, name="details"),
    path("details/<int:id>/charts/", views.charts_view, name="charts"),
    path("bidding/<int:id>/", views.bidding_view, name="bidding"),

    path("api/bids/<id>/", views.bids, name="bids"),
    path("api/bid/<id>/<int:value>/", views.bid, name="bid"),
    path("api/favorite/<id>/", views.favorite, name="favorite"),
    path("api/info/<id>/", views.get_online_data, name="online"),
    path("api/details/<id>/<type>/", views.get_auction_data, name="details"),
]

delay/seller/urls.py
from django.conf.urls import url

from delay.seller.views import (
    create_auction,
    api_create_auction,
    api_create_auction_2 
)

app_name = "seller"
urlpatterns = [
    url(r"^create-auction/$", create_auction, name="create"),
    url(r"^api/create-auction-2/$", api_create_auction_2, name="create_api_2"),
    url(r"^api/create-auction/$", api_create_auction, name="create_api"),
]

delay/users/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordResetForm

from .views import SignUpView, user_login_view, user_verify_view 

app_name = "users"

urlpatterns = [
    re_path(r"^signup/$", view=SignUpView.as_view(), name="signup"),
    re_path(r'^login/$', view=user_login_view, name='login'),
    re_path(r'^verify/$', view=user_verify_view, name='verify'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(
        r'^password_reset/$', 
        auth_views.PasswordResetView.as_view(
            form_class=PasswordResetForm,
            template_name='users/account/password_reset_form.html',
            email_template_name='users/account/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),

    re_path(
        r'^password_reset/done/$', 
        auth_views.PasswordResetDoneView.as_view(template_name="users/account/password_reset_done.html"), 
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url = reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm',
    ),

    re_path(
        r'^reset/done/$', 
        auth_views.PasswordResetCompleteView.as_view(), 
        name='password_reset_complete'
    )

]

delay/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation

from delay.users.models import User


class CustomUserCreationForm(UserCreationForm):

    error_message = UserCreationForm.error_messages.update(
        {"duplicate_phone": "Данный телефонный номер уже используется в системе"}
    )

    password2 = None

    class Meta:
        model = User
        fields = ['email', 'phone', 'password1', 'last_name', 'first_name', 'company_name', 'company_type', 'documents']

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        try:
            password_validation.validate_password(password1, self.instance)
        except forms.ValidationError as error:
            self.add_error('password1', error)
        return password1

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        try:
            User.objects.get(phone=phone)
        except User.DoesNotExist:
            return phone.replace('(', '').replace(')', '').replace('-', '')
        raise forms.ValidationError(self.error_messages["duplicate_phone"])

delay/core/views.py
from django.shortcuts import render


def error_400(request, exception):
    return render(request,'error_pages/400.html', status=400, context={})

def error_403(request, exception):
    return render(request,'error_pages/403.html', status=403, context={})

def error_404(request, exception, template_name='error_pages/404.html'):
    return render(request, template_name, locals())

def error_500(request):
    return render(request, 'error_pages/500.html', status=500, context={})

delay/lots/views.py
from django.db.utils import IntegrityError
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.generic import ListView
from django.conf import settings
from django.http import JsonResponse, HttpResponseNotFound, Http404
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.shortcuts import render

from delay.helpers import ajax_required, serialize_excel
from delay.core.models import Auction, Bid
from delay.helpers import is_owner


class BaseAuctionListView(ListView):
    model = Auction
    context_object_name = "data"
    template_name = "auction/lots.html"

    def get_queryset(self, user, auctions, **kwargs):

        if user.is_staff:
            return auctions.order_by('status', '-timestamp_finish')

        if user.is_anonymous:
            return auctions.order_by('status', '-timestamp_finish')

        user_company_type = user.company_type
        user_own_auctions = auctions.filter(user=user)
            
        if user_company_type == 'B':
            qs = auctions.filter(accepted_banks=True)
        elif user_company_type == 'M':
            qs = auctions.filter(accepted_mfo=True)
        elif user_company_type == 'C':
            qs = auctions.filter(accepted_collection_agencies=True)

        return qs.union(user_own_auctions).order_by('status', '-timestamp_finish') # TODO продумать сортировку?


class AuctionAllListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_all()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "all"
        return context


class AuctionCurrentListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        auctions = Auction.objects.get_started()
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "current"
        return context


class AuctionRelevantListView(BaseAuctionListView):
    def get_queryset(self, **kwargs):
        qs_1 = Auction.objects.get_approved()
        qs_2 = Auction.objects.get_started()
        auctions = qs_1.union(qs_2)
        return super().get_queryset(self.request.user, auctions)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["active"] = "relevant"
        return context


@login_required
def detail_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(
        request, "auction/auction_details.html", context={'card': db_data}
    )


@login_required
def bidding_view(request, id):
    auction = Auction.objects.get(id=id)
    if auction.status != '2_S':
        return render(request, "error_pages/404.html")
    is_allowed = request.user.company_type in auction.allowed_company_types
    is_auction_owner = request.user == auction.user
    if is_auction_owner:
        role = 'author'
    elif is_allowed: # в продакшене фильтровать стаффов
        role = 'bidder'
    else:
        role = 'spectator'

    return render(
        request, "auction/auction_bidding.html", context={'card': auction, 'room_name': id, 'role': role}
    )


@ajax_required
@require_http_methods(["GET"])
def bids(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    response = {}
    for ix, bid in enumerate(bids):
        response[ix] = [bid.user.phone, bid.price, bid.step, bid.time]
    return JsonResponse(response)


@ajax_required
@require_http_methods(["GET"])
def get_online_data(request, id):
    auction = Auction.objects.get(id=id)
    bids = auction.bids.all()
    bids_count = bids.count()

    if auction.closed_auction:
        if not bids_count:
            last_user_bid = auction.start_price
        else:
            last_user_bid = bids.filter(user=request.user).latest('time').price
        return JsonResponse({'count': bids_count, 'lastUserBid': last_user_bid})
    else:
        if not bids_count:
            return JsonResponse('No Bids', safe=False)
        bids_last = bids.first().price
        return JsonResponse({'count': bids_count, 'last': bids_last})


def charts_view(request, id):
    db_data = Auction.objects.get(id=id)
    if db_data.status not in ['2_S', '1_A']:
        return render(request, "error_pages/404.html")
    return render(request, "auction/auction_analysis.html", context={'card': db_data})


@login_required
@ajax_required
@require_http_methods(["GET"])
def favorite(request, id):
    auction = Auction.objects.get(id=id)
    user = request.user
    if user in auction.bookmarks.all():
        auction.bookmarks.remove(user)
    else:
        auction.bookmarks.add(user)
    return JsonResponse({"count": auction.bookmarks.count()}, status=200) # TODO шедулинг на смс


@login_required
@ajax_required
@require_http_methods(["GET"])
def bid(request, id, value):
    print(request, id, value)
    auction = Auction.objects.get(id=id)
    new_bid = Bid(user=request.user, price=value, step=value)
    try:
        new_bid.save()
        auction.bids.add(new_bid)
        auction.save()
        return JsonResponse({'code': 'success', 'message': 'Ставка принята'})
    except Exception:
        transaction.rollback()
        return JsonResponse({'code': 'error', 'message': 'Не удалось принять ставку' })



@login_required
@ajax_required
@require_http_methods(["GET"])
def get_auction_data(request, id, type):
    data = Auction.objects.get(id=id)
    document = settings.MEDIA_ROOT + '/' + data.doc_register.name
    data_dict = serialize_excel(document)
    if type == 'chart-details':
        osz_list = sorted([row['osz'] for row in data_dict])
        chart_data = [[ix, val] for ix, val in enumerate(osz_list)]
        return JsonResponse(chart_data, safe=False)
    elif type == 'chart-analysis':
        return JsonResponse({
            'sex': sorted([row['sex'] for row in data_dict]), 
            'age': sorted([row['age'] for row in data_dict]),
            'region': sorted([row['region'] for row in data_dict]),
            'osz': sorted([row['osz'] for row in data_dict]),
            'delay': sorted([row['delayPeriod'] for row in data_dict]),
            }, safe=False)
    elif type == 'datatable':
        return JsonResponse(data_dict, safe=False)

delay/seller/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.files import File


from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import FileUploadParser, MultiPartParser, FormParser


from delay.helpers import AuthorRequiredMixin, _process_excel
from delay.core.models import Auction, AuctionQuerySet

from .serializers import AuctionSerializer

from config.settings.base import MEDIA_URL


@ensure_csrf_cookie
def create_auction(request, *args, **kwargs):
    form = AuctionDocumentForm()
    return render(request, "auction/auction_create.html", {"form": form})


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser, FileUploadParser])
def api_create_auction(request, *args, **kwargs):
    file_obj = request.data['file']
    
    osz, od, region, average_debt, average_delay, n_cases, multiregion = _process_excel(file_obj)
    data = {'osz': osz, 'od': od, 'region': region, 'average_debt': average_debt, 'average_delay': average_delay, 'n_cases': n_cases, 'multiregion': multiregion}
    return Response(json.dumps(data))


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def api_create_auction_2(request, *args, **kwargs):
    serializer = AuctionSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response('OK', 200)

delay/users/views.py
import json

from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from delay.helpers import ajax_required, generate_code, send_sms

from .models import User
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    template_name = 'users/account/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')


def user_login_view(request):
    if request.method == 'GET':
        return render(request, "users/account/login.html", context={'error': None})
    phone = request.POST.get('username')
    password = request.POST.get('password')
    try:
        user = User.objects.get(phone=phone)
    except Exception:
        return render(request, "users/account/login.html", context={'error': 'Аккаунт не найден'})
    if not check_password(password, user.password):
        return render(request, "users/account/login.html", context={'error': 'Неверный пароль'})
    request.session['phone'] = phone
    request.session['password'] = password
    return redirect('users:verify')


def user_verify_view(request):
    if request.method == 'GET':
        code = '22222' # generate_code()
        phone = request.session['phone']
        cache.set(f'{phone}_otp', code, 120)
        # send_sms(code, '+79969752375') # phone
        print(phone, cache.get(f'{phone}_otp'))
        return render(request, "users/account/verify.html")
    code = request.POST.get('code')
    print(code)
    phone = request.session['phone']
    correct_code = cache.get(f'{phone}_otp')
    if not correct_code:
        return render(request, "users/account/verify.html", context={'error': "Срок действия кода вышел. Мы отправили Вам новый"})
    if correct_code != code:
        return render(request, "users/account/verify.html", context={'error': "Неверный код. Мы отправили Вам новый"})
    user = authenticate(request, username=phone, password=request.session['password'])
    if not user:
        return render(request, "users/account/login.html", context={'error': 'Возникли проблемы при входе в аккаунт. Попробуйте еще раз'})
    login(request, user)
    print(user)
    return redirect('lots:all')

delay/templates/auction/auction_analysis.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}Информация об аукционе{% endblock %}

{% block head %} <link href="{% static './css/lots.css' %}" rel="stylesheet"> {% endblock head %}

{% block content %}
<div hidden id="overlay" class="overlay"></div>
<div hidden id="spinner" class="spinner"></div>
{% include '../_base_components/_user_navbar.html' %}
<div class="grid grid-analysis">

    <a href="{% url 'lots:details' card.id %}" class="datatable__back__link datatable__back__link-mobile">
        <svg class="datatable__back__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16l-4-4m0 0l4-4m-4 4h18"></path>
        </svg>
        К странице информации
    </a>

    <div class="datatable" x-data="datatables()" x-init="init()" x-cloak>
        <div class="datatable__ui">
            <div class="datatable__filter">
                <button class="datatable__filter__button" @click.prevent="open = !open">
                    <span class="block">Filter</span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="datatable__filter__icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                        <polyline points="6 9 12 15 18 9" />
                    </svg>
                </button>
                <div class="datatable__filter__items" x-show="open" @click.away="open = false">
                    <template x-for="heading in headings">
                        <label class="datatable__filter__item">
                            <input class="datatable__filter__checkbox" type="checkbox" checked @click="toggleColumn(heading.key)">
                            <div class="datatable__filter__value" x-text="heading.value"></div>
                        </label>
                    </template>
                </div>
            </div>
            <a href="{% url 'lots:details' card.id %}" class="datatable__back__link">
                <svg class="datatable__back__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16l-4-4m0 0l4-4m-4 4h18"></path>
                </svg>
                К странице информации
            </a>
        </div>
        <div class="datatable__content scrollbar scrollbar-datatable">
            <table class="datatable__table">
                <thead>
                    <tr class="text-left">
                        <template x-for="heading in headings">
                            <th class="datatable__table__heading" x-text="heading.value" :x-ref="heading.key" :class="{ [heading.key]: true }"></th>
                        </template>
                    </tr>
                </thead>
                <tbody>
                    <template x-for="col in cols" :key="col">
                        <tr>
                            <td class="datatable__column region"><span class="datatable__column__text" x-text="col.region"></span></td>
                            <td class="datatable__column age"><span class="datatable__column__text" x-text="col.age"></span></td>
                            <td class="datatable__column sex"><span class="datatable__column__text" x-text="col.sex"></span></td>
                            <td class="datatable__column sumOfLoan"><span class="datatable__column__text" x-text="col.sumOfLoan"></span></td>
                            <td class="datatable__column osz"><span class="datatable__column__text" x-text="col.osz"></span></td>
                            <td class="datatable__column od"><span class="datatable__column__text" x-text="col.od"></span></td>
                            <td class="datatable__column delayPeriod"><span class="datatable__column__text" x-text="col.delayPeriod"></span></td>
                            <td class="datatable__column lastPayment"><span class="datatable__column__text" x-text="col.lastPayment"></span></td>
                            <td class="datatable__column judgeAct"><span class="datatable__column__text" x-text="col.judgeAct"></span></td>
                            <td class="datatable__column id"><span class="datatable__column__text" x-text="col.id"></span></td>
                        </tr>
                    </template>
                </tbody>
            </table>
        </div>
    </div>

    <div class="analysis__plots">
        <div class="analysis__plot analysis__plot-2 osz-plot "></div>
        <div class="analysis__plot analysis__plot-2 delay-plot"></div>
        <div class="analysis__plot analysis__plot-3 sex-plot"></div>
        <div class="analysis__plot analysis__plot-3 region-plot"></div>
        <div class="analysis__plot analysis__plot-3 age-plot"></div>
    </div>

</div>
{{ card.id|json_script:"card-id" }}

{% endblock content %}


{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src="{% static 'js/auction_analysis.js' %}"></script>
{% endblock javascript %}

delay/templates/auction/auction_bidding.html
{% extends 'base.html' %} {% load static humanize %} {% block title %}Ставки{% endblock %}
{% block head %}
<link href="{% static 'css/lots.css' %}" rel="stylesheet" />
<link href="{% static 'css/bidding.css' %}" rel="stylesheet" />
{% endblock head %} {% block content %}
<div hidden id="overlay" class="overlay"></div>
<div hidden id="spinner" class="spinner"></div>
{% include '../_base_components/_user_navbar.html' %}
<div class="grid grid-bidding">
    <div class="bidding__heading">
        <div class="bidding__heading__left">
            <div class="bidding__title">
                <div class="bidding__title__lot">
                    <span class="bidding__title__id">Аукцион #{{ card.id }}</span>
                    <span class="bidding__dot">
                        <svg class="bidding__dot__icon" width="10" height="10"><circle cx="5" cy="5" r="5" fill="currentColor"></circle></svg>
                    </span>
                </div>
                <span class="bidding__title__company">ООО "{{ card.user.company_name }}"</span>
            </div>
        </div>
        <div class="countdown" x-data="timer(new Date('{{ card.timestamp_finish.isoformat }}'))" x-init="init();">
            <div class="countdown__heading"></div>
            <div class="countdown__data flex">
                <div class="countdown__block">
                    <span class="countdown__title">дней</span>
                    <div class="countdown__number" x-text="time().days"></div>
                </div>
                <div class="countdown__block">
                    <span class="countdown__title">часов</span>
                    <div class="countdown__number" x-text="time().hours1"></div>
                    <div class="countdown__number" x-text="time().hours2"></div>
                </div>
                <div class="countdown__block">
                    <span class="countdown__title">минут</span>
                    <div class="countdown__number" x-text="time().minutes1"></div>
                    <div class="countdown__number" x-text="time().minutes2"></div>
                </div>
                <div class="countdown__block">
                  <span class="countdown__title">секунд</span>
                  <div class="countdown__number" x-text="time().seconds1"></div>
                  <div class="countdown__number" x-text="time().seconds2"></div>
              </div>

            </div>
        </div>
        <div class="bidding__alert bidding__alert-hidden">
            <div class="bidding__alert__content" role="alert">
                <span class="bidding__alert__icon">
                    <svg class="bidding__alert__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="#333333">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
                    </svg>
                </span>
                <span class="bidding__alert__text"></span>
            </div>
        </div>
    </div>

    <div class="bidding__main">
        <section class="bidding__messages"></section>
        <section class="bidding__sidebar" x-data="{open: false}" x-cloak>
            <div class="bidding__sidebar__content" :class="{ 'bidding__sidebar__content-active': open}" x-show="open">
                <p class="bidding__sidebar__title"> Информация об аукционе </p>
                {% include '_base_components/_lot_details_table.html' %}
            </div>
            <button class="bidding__sidebar__button" :class="{ 'border border-l-0': open }" role="button" @click="open = !open" title="Информация о лоте">
                <svg class="bidding__sidebar__button__icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
            </button>
        </section>
    </div>

    <div class="bidding__footer">
    {% if role == 'bidder' %} 
        <div class="bidding__ui">
          <input class="bidding__ui__input" type="radio" id="bid25" name="bid" />
          <label for="bid25" class="bidding__ui__label">25 000</label>
        </div>
        <div class="bidding__ui">
          <input class="bidding__ui__input" type="radio" id="bid50" name="bid" />
          <label for="bid50" class="bidding__ui__label">50 000</label>
        </div>
        <div class="bidding__ui">
          <input class="bidding__ui__input" type="radio" id="bid100" name="bid" />
          <label for="bid100" class="bidding__ui__label">100 000</label>
        </div>      
        <button class="bidding__ui__button" type="button" id="bid-submit" disabled>Сделать ставку!</button>
    {% elif role == 'author' %}
        <p class="bidding__footer__text">Вы не можете участвовать в собственных торгах</p>
    {% else %}
        <p class="bidding__footer__text">К сожалению, вы не можете участвовать в данных торгах</p>
    {% endif %}
    </div>
</div>
{{ role|json_script:"user-role" }} 
{{ room_name|json_script:"room-name" }} 
{{ card.id|json_script:"card-id" }} 
{{ request.user.phone|json_script:"user-phone" }}
{{ card.start_price|json_script:"start-price" }} 
{% endblock content %} 

{% block javascript %}<script src="{% static 'js/bidding.js' %}"></script>{% endblock javascript %}

delay/templates/auction/auction_details.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}Информация об аукционе{% endblock %}

{% block head %}
<link href="{% static 'css/lots.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
{% include '../_base_components/_user_navbar.html' %}
<div class="grid grid-details">
  <section class="details__infographics">
  {% include '../_base_components/_card-small.html' %}
  </section>
  <section class="details__content">
    <div class="details__content__heading">
      <h3 class="details__content__title"> Аукцион #{{ card.id }} </h3>
      <a href="{% url 'lots:charts' card.id %}" class="details__link details__link-analysis">
        <svg class="details__link__svg" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"></path>
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"></path>
        </svg>
        Аналитика портфеля
      </a>
    </div>
    {% include '_base_components/_lot_details_table.html' %}        
  </section>

</div>
{{ card.id|json_script:"card-id" }}
{% endblock content %}

{% block javascript %}{% endblock javascript %}

delay/templates/auction/lots.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}Все торги{% endblock %}
{% block head %} <link href="{% static 'css/lots.css' %}" rel="stylesheet"> {% endblock head %}

{% block content %}
{% include '../_base_components/_user_navbar.html' %}
<div class="grid-lots">
  
  <div class="tabs">
    <a href="{% url 'lots:relevant' %}" class="tabs__item {% if active == 'relevant' %} tabs__item-active {% endif %}">
      Актуальные {% if active == 'relevant' %} &middot {% endif %}
    </a>
    <a href="{% url 'lots:current' %}" class="tabs__item {% if active == 'current' %} tabs__item-active {% endif %}">
      Идут торги {% if active == 'current' %} &middot {% endif %}
    </a>
    <a href="{% url 'lots:all' %}" class="tabs__item {% if active == 'all' %} tabs__item-active {% endif %}">
      Все торги {% if active == 'all' %} &middot {% endif %}
    </a>
  </div>
  <div class="cards scrollbar">
    {% for card in data %}
      {% include "_base_components/_card.html" with card=card %}
    {% empty %}
      {% if active == "current" %}
      <div class="cards__alert">В данный момент торги не проводятся. Ознакомьтесь с предстоящими торгами!</div>
      {% elif active == "relevant" %}
      <div class="cards__alert">В данный момент на платформе нет актуальных для вас торгов</div>
      {% endif %}
    {% endfor %}
  </div>
</div>
<div id="msgbox-area" class="msgbox-area"></div>


{% endblock content %}

{% block javascript %}
<script src="https://unpkg.com/element-closest"></script>
<script src="{% static 'js/lots.js' %}"></script>
{% endblock javascript %}